# Change these first
owner: loftwah # Your GitHub organization or username, where this repository lives
repo: loftwah-upptime # The name of this repository

sites:
  - name: Loftwah The Beatsmiff
    url: https://beatsmiff.com
  - name: Grind Mode Cypher
    url: https://grindmodecypher.com
  - name: Grind Mode Cypher Shop
    url: https://shop.grindmodecypher.com
  - name: Lofts.sh
    url: https://lofts.sh
  - name: Mad Fap Entertainment
    url: https://madfapentertainment.com
  - name: Perth Card Grading
    url: https://perthcardgrading.com.au
  - name: Shake Down Records
    url: https://shakedownrecords.com.au
  - name: Shake Down Studio
    url: https://shakedownstudio.com.au

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: uptime.lofts.sh
  baseUrl: /loftwah-upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Loftwah's Upptime
  introTitle: "**Loftwah's Upptime** is a status page for Loftwah's services"
  introMessage: This is my personal website status page. It is powered by [Upptime](https://upptime.js.org) and hosted on GitHub Pages.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
